spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/pms_db;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: Stephane0412
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
